# Generated by Django 4.2.1 on 2023-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rdate", models.DateField()),
                ("movieName", models.CharField(max_length=50)),
                ("hero", models.CharField(max_length=20)),
                ("heroine", models.CharField(max_length=20)),
                ("rating", models.IntegerField()),
            ],
        ),
    ]
